[package]
name = "lancelot_life"
version = "0.1.0"
authors = ["Lancelot OWCZARCZAK <lowczarc@student.42.fr>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
lazy_static = "1.3.0"
mysql = "16.0.2"
chrono = "0.4.6"

[build-dependencies]
regex = "1.1.6"
